deployment:
  apiVersion: "apps/v1"
  
ingress:
  apiversion: networking.k8s.io/v1

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

operations_web:
  enabled: true
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-ops-web"
  imageTag: "latest"
  SPRING_PROFILES_ACTIVE: "bb"
  hostname: "ops.sandbox.fynarfin.io"
  webhost: "ops.sandbox.fynarfin.io"
  limits:
    cpu: "500m"
    memory: "512M"
  requests:
    cpu: "100m"
    memory: "256M"
  ingress:
    className: "kong"
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
      konghq.com/plugins: request-transformer,oidc,cors
    tls:
      - secretName: sandbox-secret 
    path: "/"
    backend:
      service:
        name: ph-ee-operations-web
        port:
          number: 4200
  deployment:
    config: {}

identity:
  hostname: "ops-bk.sandbox.fynarfin.io"