# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.ph_ee_connector_ams_mifos.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: {{ template " ph-ee-connector-ams-mifos.fullname" . }}
  labels:
    app: {{ template " ph-ee-connector-ams-mifos.fullname" . }}
spec:
  replicas: {{ .Values.ph_ee_connector_ams_mifos.replicas }}
  selector:
    matchLabels:
      app: {{ template " ph-ee-connector-ams-mifos.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template " ph-ee-connector-ams-mifos.fullname" . }}
      annotations:
{{- if .Values.ph_ee_connector_ams_mifos.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_ams_mifos.deployment.annotations | indent 8 }}
{{- end }}
        # {{- if or  .Values.ph_ee_connector_ams_mifosConfig .Values.deployment.ph-ee-connector-ams-mifosConfig }}
        # configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        # {{- end }}
    spec: 
      affinity: {{ toYaml .Values.ph_ee_connector_ams_mifos.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.ph_ee_connector_ams_mifos.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.ph_ee_connector_ams_mifos.tolerations | default .Values.ph_ee_connector_ams_mifos.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.ph_ee_connector_ams_mifos.priorityClassName }}
      priorityClassName: {{ .Values.ph_ee_connector_ams_mifos.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template " ph-ee-connector-ams-mifos.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.ph_ee_connector_ams_mifos.terminationGracePeriod }}  
      containers:
        - name: ph-ee-connector-ams-mifos
          image: "{{ .Values.ph_ee_connector_ams_mifos.image }}:{{ .Values.ph_ee_connector_ams_mifos.imageTag }}"
          imagePullPolicy: "{{ .Values.ph_ee_connector_ams_mifos.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources: {{ toYaml ( .Values.ph_ee_connector_ams_mifos.resources | default .Values.ph_ee_connector_ams_mifos.deployment.resources ) | nindent 10 }}
      {{- if .Values.ph_ee_connector_ams_mifos.imagePullSecrets }}
          imagePullSecrets:
    {{ toYaml .Values.ph_ee_connector_ams_mifos.imagePullSecrets | indent 8 }}
        {{- end }}
          livenessProbe:
{{ toYaml .Values.ph_ee_connector_ams_mifos.livenessProbe | indent 10 }}
          readinessProbe:
{{ toYaml .Values.ph_ee_connector_ams_mifos.readinessProbe | indent 10 }}  
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_connector_ams_mifos.SPRING_PROFILES_ACTIVE }}"
            - name: "ams_local_enabled"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_enabled }}"
            - name: "ams_local_interop_host"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_interop_host }}"
            - name: "ams_local_customer_host"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_customer_host }}"
            - name: "ams_local_account_host"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_account_host }}"
            - name: "ams_local_auth_host"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_auth_host }}"
            - name: "ams_local_loan_host"
              value: "{{ .Values.ph_ee_connector_ams_mifos.ams_local_loan_host }}"
            - name: "dfspids"
              value: "{{ .Values.ph_ee_connector_ams_mifos.dfspids }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- if .Values.ph_ee_connector_ams_mifos.extraEnvs | default .Values.ph_ee_connector_ams_mifos.deployment.extraEnvs }}
{{ toYaml ( .Values.ph_ee_connector_ams_mifos.extraEnvs | default .Values.ph_ee_connector_ams_mifos.deployment.extraEnvs ) | indent 8 }}
{{- end }}
          envFrom: {{ toYaml ( .Values.ph_ee_connector_ams_mifos.envFrom | default .Values.ph_ee_connector_ams_mifos.deployment.envFrom ) | nindent 10 }}
          securityContext: {{ toYaml ( .Values.ph_ee_connector_ams_mifos.podSecurityContext | default .Values.ph_ee_connector_ams_mifos.deployment.securityContext ) | nindent 10 }}

          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
{{- if .Values.ph_ee_connector_ams_mifos.deployment.config }}
{{ toYaml .Values.ph_ee_connector_ams_mifos.deployment.config | indent 12 }}
{{- end }}            
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
            - -timeout=120s
            - -wait
            - tcp://{{ .Values.operations_app.datasource.host }}:3306
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
    {{ tpl .Values.extraInitContainers . | indent 6 }}
          {{- else }}
    {{ toYaml .Values.extraInitContainers | indent 6 }}
          {{- end }}
          {{- end }}          
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
     {{- if .Values.ph_ee_connector_ams_mifos.extraVolumeMounts | default .Values.ph_ee_connector_ams_mifos.deployment.extraVolumeMounts }}
  {{ toYaml ( .Values.ph_ee_connector_ams_mifos.extraVolumeMounts | default .Values.ph_ee_connector_ams_mifos.deployment.extraVolumeMounts ) | indent 8 }}
          {{- end }}
        {{- if .Values.ph_ee_connector_ams_mifos.extraContainers }}
  {{ tpl .Values.ph_ee_connector_ams_mifos.extraContainers . | indent 6 }}
        {{- end }}

{{- end }}            