{{- if .Values.ph_ee_connector_gsma.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-gsm"
  labels:
    app: "ph-ee-connector-gsm"
spec:
  replicas: {{ .Values.ph_ee_connector_gsma.replicas }}
  selector:
    matchLabels:
      app: "ph-ee-connector-gsm"
  template:
    metadata:
      labels:
        app: "ph-ee-connector-gsm"
      annotations:
{{- if .Values.ph_ee_connector_gsma.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_gsma.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: "ph-ee-connector-gsma-mm"
          image: "{{ .Values.ph_ee_connector_gsma.image }}:{{ .Values.ph_ee_connector_gsma.imageTag }}"
          imagePullPolicy: "{{ .Values.ph_ee_connector_gsma.imagePullPolicy }}"
          ports:
            - containerPort: 5000 
          resources:
            limits:
              memory: "{{ .Values.ph_ee_connector_gsma.limits.memory }}"
              cpu: "{{ .Values.ph_ee_connector_gsma.limits.cpu }}"
            requests:
              memory: "{{ .Values.ph_ee_connector_gsma.requests.memory }}"
              cpu: "{{ .Values.ph_ee_connector_gsma.requests.cpu }}"              
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8080
            initialDelaySeconds: 20
            periodSeconds: 30
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_connector_gsma.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- end }}            