{{- if .Values.ph_ee_connector_gsma.enabled -}}

apiVersion: apps/v1
kind: Deployment
metadata:
  name: "ph-ee-connector-gsma"
  labels:
    app: ph-ee-connector-gsma
spec:
  replicas: {{ .Values.ph_ee_connector_gsma.replicas }}
  selector:
    matchLabels:
      app: ph-ee-connector-gsma
  template:
    metadata:
      labels:
        app: ph-ee-connector-gsma
      annotations:
{{- if .Values.ph_ee_connector_gsma.deployment.annotations }}
{{ toYaml .Values.ph_ee_connector_gsma.deployment.annotations | indent 8 }}
{{- end }}
    spec:
      containers:
        - name: ph-ee-connector-gsma-mm
          image:  "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-gsma"
          imagePullPolicy: "{{ .Values.ph_ee_connector_gsma.imagePullPolicy }}"
          ports:
            - containerPort: 5000
          resources:
            limits:
              cpu: "500m"
              memory: "512M"
            requests:
              cpu: "100m"
              memory: "256M"
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.ph_ee_connector_gsma.SPRING_PROFILES_ACTIVE }}"
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
{{- end }}            