deployment:
  apiVersion: "apps/v1"
  
ingress:
  apiversion: networking.k8s.io/v1

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

roster_connector:
  enabled: true
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-roster"
  imageTag: latest
  SPRING_PROFILES_ACTIVE: "bb"
  ams:
    local:
      enabled: true
  pesacore:
    auth_header: "PaymentHub"
  limits:
    cpu: "500m"
    memory: "512M"
  requests:
    cpu: "100m"
    memory: "256M"
  deployment:
    annotations:
      deployTime: "{{ .Values.deployTime }}"  