{{- if .Values.mpesa.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-connector-mpesa
  annotations:
{{- if .Values.mpesa.ingress.annotations }}
{{ toYaml .Values.mpesa.ingress.annotations | indent 4 }}
{{- end }}

spec:
  rules:
    - host: "{{ .Values.mpesa.hostname }}"
      http:
        paths:
        - path: "{{ .Values.mpesa.ingress.path }}"
          pathType: Prefix
          backend:
{{- if .Values.mpesa.ingress.backend }}
{{ toYaml .Values.mpesa.ingress.backend | indent 14 }}
{{- end }}

  tls:
  - hosts:
    - "{{ .Values.mpesa.wildcardhostname }}"
    secretName: "{{ .Values.mpesa.tls }}"
{{- end }}