deployment:
  apiVersion: "apps/v1"
  
ingress:
  apiversion: networking.k8s.io/v1

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"
  
notifications:
  enabled: false
  replicas: 1
  image: ""
  imageTag: "v1.0.2"
  imagePullPolicy: "Always"
  SPRING_PROFILES_ACTIVE: ""
  LOGGING_LEVEL_ROOT: "INFO"
  hostname: ""
  zeebe_broker_contactpoint: "zeebe-zeebe-gateway:26500"
  MESSAGEGATEWAYCONFIG_HOST: "message-gateway"
  NOTIFICATION_LOCAL_HOST: "ph-ee-connector-notifications"
  NOTIFICATION_SUCCESS_ENABLED: "false"
  NOTIFICATION_FAILURE_ENABLED: "true"
  hostconfig:
    host: ""
    port: ""
  limits:
    memory: "512M"
    cpu: "500m"
  requests:
    memory: "512M"
    cpu: "100m"
  ingress:
    enabled: false
    path: "/notifications"
    annotations: {}
    backend: {}
  deployment:
    annotations: {}