apiVersion: v1
appVersion: "0.0.0"
description: PaymentHub EE Engine
name: ph-ee-engine
version: 0.0.0-SNAPSHOT
dependencies:
  - name: gsma
    version: 1.0.0
    repository: "file://./connector-gsma"
  - name: notifications
    version: 1.0.0
    repository: "file://./connector-notifications"
  - name: paygops
    version: 1.0.0
    repository: "file://./ams-paygops"
  - name: roster
    version: 1.0.0
    repository: "file://./ams-roster"  
  - name: mpesa
    version: 1.0.0
    repository: "file://./connector-mpesa" 
  - name: operations-app
    version: 1.0.0
    repository: "file://./operations-app"
  - name: operations-web
    version: 1.0.0
    repository: "file://./operations-web" 
  - name: mojaloop
    version: 1.0.0
    repository: "file://./connector-mojaloop"  
  - name: slcb
    version: 1.0.0
    repository: "file://./connector-slcb" 
  - name: importer-es
    version: 1.0.0
    repository: "file://./operations-importer-es"   