apiVersion: {{ .Values.secret.apiversion }}
kind: Secret
metadata:
  name: bulk-processor-secret
type: Opaque
data:
  aws-access-key: {{ .Values.connector_bulk.aws-access-key | b64enc }}
  aws-secret-key: {{ .Values.connector_bulk.aws-secret-key | b64enc }}
