# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.operations.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: {{ template "ph-ee-importer-rdbms.fullname" . }}
  labels:
    app: {{ template "ph-ee-importer-rdbms.fullname" . }}
spec:
  replicas: {{ .Values.importer_rdbms.replicas }}
  selector:
    matchLabels:
      app: {{ template "ph-ee-importer-rdbms.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template "ph-ee-importer-rdbms.fullname" . }}
      annotations:
{{- if .Values.importer_rdbms.deployment.annotations }}
{{ toYaml .Values.importer_rdbms.deployment.annotations | indent 8 }}
{{- end }}
        # {{- if or  .Values.ph-ee-importer-rdbmsConfig .Values.deployment.ph-ee-importer-rdbmsConfig }}
        # configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        # {{- end }}
    spec:
      affinity: {{ toYaml .Values.importer_rdbms.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.importer_rdbms.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.importer_rdbms.tolerations | default .Values.importer_rdbms.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.importer_rdbms.priorityClassName }}
      priorityClassName: {{ .Values.importer_rdbms.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template "ph-ee-importer-rdbms.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.importer_rdbms.terminationGracePeriod }}      

      containers:
        - name: ph-ee-importer-rdbms
          image: "{{ .Values.importer_rdbms.image }}:{{ .Values.importer_rdbms.imageTag }}"
          imagePullPolicy: "{{ .Values.importer_rdbms.imagePullPolicy }}"
          resources: {{ toYaml ( .Values.importer_rdbms.resources | default .Values.importer_rdbms.deployment.resources ) | nindent 10 }}
          ports:
            - containerPort: 8000
          {{- if .Values.imagePullSecrets }}
          imagePullSecrets:
    {{ toYaml .Values.importer_rdbms.imagePullSecrets | indent 8 }}
        {{- end }}            
          livenessProbe:
{{ toYaml .Values.importer_rdbms.livenessProbe | indent 10 }}
          readinessProbe:
{{ toYaml .Values.importer_rdbms.readinessProbe | indent 10 }}
          env:
            - name: "SPRING_PROFILES_ACTIVE"
              value: "{{ .Values.operations.SPRING_PROFILES_ACTIVE }}"
            - name: "DATASOURCE_CORE_USERNAME"
              value: "{{ .Values.importer_rdbms.datasource.username }}" 
            - name: "DATASOURCE_CORE_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "importer-rdbms-secret"
                  key: "database-password"
            - name: "DATASOURCE_CORE_HOST"
              value: "{{ .Values.importer_rdbms.datasource.host }}"
            - name: "DATASOURCE_CORE_PORT"
              value: "{{ .Values.importer_rdbms.datasource.port }}"
            - name: "DATASOURCE_CORE_SCHEMA"
              value: "{{ .Values.importer_rdbms.datasource.schema }}"
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.importer_rdbms.LOGGING_LEVEL_ROOT }}"
            - name: "LOGGING_PATTERN_CONSOLE"
              value: "{{ .Values.importer_rdbms.LOGGING_PATTERN_CONSOLE }}"
            - name: "JAVA_TOOL_OPTIONS"
              value: "{{ .Values.importer_rdbms.javaToolOptions}}"
{{- if .Values.importer_rdbms.extraEnvs | default .Values.importer_rdbms.deployment.extraEnvs }}
{{ toYaml ( .Values.importer_rdbms.extraEnvs | default .Values.importer_rdbms.deployment.extraEnvs ) | indent 8 }}
{{- end }}
          envFrom: {{ toYaml ( .Values.importer_rdbms.envFrom | default .Values.importer_rdbms.deployment.envFrom ) | nindent 10 }}
          securityContext: {{ toYaml ( .Values.importer_rdbms.podSecurityContext | default .Values.importer_rdbms.deployment.securityContext ) | nindent 10 }}
          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
{{- if .Values.importer_rdbms.deployment.config }}
{{ toYaml .Values.importer_rdbms.deployment.config | indent 12 }}
{{- end }}               

      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
     {{- if .Values.importer_rdbms.extraVolumeMounts | default .Values.importer_rdbms.deployment.extraVolumeMounts }}
  {{ toYaml ( .Values.importer_rdbms.extraVolumeMounts | default .Values.importer_rdbms.deployment.extraVolumeMounts ) | indent 8 }}
          {{- end }}
        {{- if .Values.importer_rdbms.extraContainers }}
  {{ tpl .Values.importer_rdbms.extraContainers . | indent 6 }}
        {{- end }} 
               
{{- end }}