{{- if .Values.notifications.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-notifications
  annotations:
{{- if .Values.notifications.ingress.annotations }}
{{ toYaml .Values.notifications.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.notifications.hostname }}"
      http:
        paths:
          - path: "{{ .Values.notifications.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.notifications.ingress.backend }}
{{ toYaml .Values.notifications.ingress.backend | indent 14 }}
{{- end }} 

  tls:
  - hosts:
    - "{{ .Values.notifications.wildcardhostname }}"
    secretName: "{{ .Values.notifications.tls }}"
{{- end }}


