deployment:
  apiVersion: "apps/v1"
  
ingress:
  apiversion: networking.k8s.io/v1

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

ph_ee_connector_ams_mifos:
  enabled: true
  image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/ph-ee-ams"
  imageTag: latest
  imagePullPolicy: "always"
  SPRING_PROFILES_ACTIVE: "fin12"
  hostname: "amsmifos.sandbox.fynarfin.io"
  ams_local_enabled: true
  ams_local_interop_host : "https://fynams.sandbox.fynarfin.io"
  ams_local_customer_host : "https://fynams.sandbox.fynarfin.io"
  ams_local_account_host : "https://fynams.sandbox.fynarfin.io"
  ams_local_auth_host : "https://fynams.sandbox.fynarfin.io"
  ams_local_loan_host : "https://fynams.sandbox.fynarfin.io/"
  dfspids: "gorilla,rhino"
  ## tenants properties have been moved to fin12
  limits:
    cpu: "500m"
    memory: "512M"
  requests:
    cpu: "100m"
    memory: "256M"
  ingress:
    enabled: true
    annotations:
      kubernetes.io/ingress.class: "nginx"
    tls:
    - hosts: "amsmifos.sandbox.mifos.io"
    - secretName: sandbox-secret
    path: "/"
    backend:
      service:
        name: ph-ee-connector-ams-mifos
        port:
          number: 80      
  deployment:
    annotations:
      deployTime: "{{ .Values.deployTime }}"

operations_app:
  datasource:
    host: "operationmysql"
keycloak:
  enabled: true     