deployment:
  apiVersion: "apps/v1"
  
ingress:
  apiversion: networking.k8s.io/v1

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"

connector_bulk:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-bulk-processor"
    SPRING_PROFILES_ACTIVE: "bb"
    imageTag: latest
    tenants: "gorilla,lion"
    hostname: "bulk-connector.sandbox.fynarfin.io"
    aws-access-key: ""
    aws-secret-key: ""
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    ingress:
      enabled: true
      className: "kong"
      annotations: 
        kubernetes.io/ingress.class: "nginx"
        konghq.com/plugins: cors
      tls:
        - secretName: sandbox-secret
      path: "/"
      backend:
        service:
          name: ph-ee-connector-bulk
          port:
            number: 80
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"
