{{- if .Values.operations_app.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-operations-app
  annotations:
{{- if .Values.operations_app.ingress.annotations }}
{{ toYaml .Values.operations_app.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.operations_app.hostname }}"
      http:
        paths:
          - path: "{{ .Values.operations_app.ingress.path }}"
            pathType: Prefix
            backend:
{{- if .Values.operations_app.ingress.backend }}
{{ toYaml .Values.operations_app.ingress.backend | indent 14 }}
{{- end }}              

  tls:
  - hosts:
    - "{{ .Values.operations_app.wildcardhostname }}"
    secretName: "{{ .Values.operations_app.tls }}"

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ph-ee-identity
  annotations:
{{- if .Values.operations_app.ingress.annotations }}
{{ toYaml .Values.operations_app.ingress.annotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: "{{ .Values.operations_app.hostname }}"
      http:
        paths:
          - path: /identity
            pathType: Prefix
            backend:
{{- if .Values.operations_app.ingress.backend }}
{{ toYaml .Values.operations_app.ingress.backend | indent 14 }}
{{- end }} 

  tls:
  - hosts:
    - "{{ .Values.operations_app.wildcardhostname }}"
    secretName: "{{ .Values.operations_app.tls }}"

{{- end }}