deployment:
  apiVersion: "apps/v1"
  
ingress:
  apiversion: networking.k8s.io/v1

service:
  apiversion: "v1"

secret:
  apiversion: "v1"

configmap:
  apiversion: "v1"
  
kafka:
  enabled: true
  image: "spotify/kafka"
  advertised:
    host: "kafka"
    port: "9092"
  limits:
    cpu: "500m"
    memory: "1G"
  requests:
    cpu: "100m"
    memory: "512M"
  deployment:
    annotations:
      deployTime: "{{ .Values.deployTime }}"