 ph_ee_connector_gsma:
    enabled: true
    image: "419830066942.dkr.ecr.ap-south-1.amazonaws.com/phee-gsma"
    imageTag: latest
    SPRING_PROFILES_ACTIVE: "bb"
    api:
      channel: ""
    limits:
      cpu: "500m"
      memory: "512M"
    requests:
      cpu: "100m"
      memory: "256M"
    deployment:
      annotations:
        deployTime: "{{ .Values.deployTime }}"