# Deploy singleton instance in the whole cluster for some unique data sources, like aws input
{{- if .Values.messagegateway.enabled -}}

apiVersion: {{ .Values.deployment.apiversion }}
kind: Deployment
metadata:
  name: {{ template " message-gateway.fullname" . }}
  labels:
    app: {{ template " message-gateway.fullname" . }}
spec:
  replicas: {{ .Values.messagegateway.replicas }}
  selector:
    matchLabels:
      app: {{ template " message-gateway.fullname" . }}
  template:
    metadata:
      labels:
        app: {{ template " message-gateway.fullname" . }}
      annotations:
{{- if .Values.messagegateway.deployment.annotations }}
{{ toYaml .Values.messagegateway.deployment.annotations | indent 8 }}
{{- end }}
        # {{- if or  .Values.messagegatewayConfig .Values.deployment.message-gatewayConfig }}
        # configChecksum: {{ include (print .Template.BasePath "/configmap.yaml") . | sha256sum | trunc 63 }}
        # {{- end }} 

    spec:
      affinity: {{ toYaml .Values.messagegateway.deployment.affinity | nindent 8 }}
      nodeSelector: {{ toYaml .Values.messagegateway.deployment.nodeSelector | nindent 8 }}
      tolerations: {{ toYaml ( .Values.messagegateway.tolerations | default .Values.messagegateway.deployment.tolerations ) | nindent 8 }}
      {{- if .Values.messagegateway.priorityClassName }}
      priorityClassName: {{ .Values.messagegateway.priorityClassName  }}
      {{- end }}
      serviceAccountName: {{ template " message-gateway.serviceAccount" . }}
      terminationGracePeriodSeconds: {{ .Values.messagegateway.terminationGracePeriod }}
      containers:
        - name: message-gateway
          image: "{{ .Values.messagegateway.image }}:{{ .Values.messagegateway.imageTag }}"  
          ports:
            - containerPort: 9191
          imagePullPolicy: "{{ .Values.messagegateway.imagePullPolicy }}"
          resources: {{ toYaml ( .Values.messagegateway.resources | default .Values.messagegateway.deployment.resources ) | nindent 10 }}
      {{- if .Values.messagegateway.imagePullSecrets }}
          imagePullSecrets:
    {{ toYaml .Values.messagegateway.imagePullSecrets | indent 8 }}
        {{- end }}
          livenessProbe:
{{ toYaml .Values.messagegateway.livenessProbe | indent 10 }}
          readinessProbe:
{{ toYaml .Values.messagegateway.readinessProbe | indent 10 }}
          env:
            - name: "SPRING_DATASOURCE_URL"
              value: "{{ .Values.messagegateway.DATASOURCE_URL }}"
            - name: "MYSQL_USERNAME"
              value: "{{ .Values.messagegateway.MYSQL_USERNAME }}"
            - name: "MYSQL_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: "messagegateway-secret"
                  key: "database-password"
            - name: "CALLBACKCONFIG_HOST"
              value: "{{ .Values.messagegateway.CALLBACKCONFIG_HOST }}"
            - name: "HOSTCONFIG_HOST"
              value: "{{ .Values.messagegateway.HOSTCONFIG_HOST }}"
            - name: "PROVIDERSOURCE_FROMDATABASE"
              value: "{{ .Values.messagegateway.PROVIDERSOURCE_FROMDATABASE }}"
            - name: "PROVIDERSOURCE_FROMYML"
              value: "{{ .Values.messagegateway.PROVIDERSOURCE_FROMYML }}"
            - name: "LOGGING_LEVEL_ROOT"
              value: "{{ .Values.messagegateway.LOGGING_LEVEL_ROOT }}"
            - name: "PROVIDERKEYS_TELERIVETAPIKEY"
              valueFrom:
                secretKeyRef:
                  name: "messagegateway-secret"
                  key: "api-key"
            - name: "PROVIDERKEYS_TELERIVETPROJECTID"
              valueFrom:
                secretKeyRef:
                  name: "messagegateway-secret"
                  key: "project-id"
{{- if .Values.messagegateway.extraEnvs | default .Values.messagegateway.deployment.extraEnvs }}
{{ toYaml ( .Values.messagegateway.extraEnvs | default .Values.messagegateway.deployment.extraEnvs ) | indent 8 }}
{{- end }}
          envFrom: {{ toYaml ( .Values.messagegateway.envFrom | default .Values.messagegateway.deployment.envFrom ) | nindent 10 }}
          securityContext: {{ toYaml ( .Values.messagegateway.podSecurityContext | default .Values.messagegateway.deployment.securityContext ) | nindent 10 }}

          volumeMounts:
            - name: ph-ee-config
              mountPath: "/config"
{{- if .Values.messagegateway.deployment.config }}
{{ toYaml .Values.messagegateway.deployment.config | indent 12 }}
{{- end }}            
      initContainers:
        - name: wait-db
          image: jwilder/dockerize
          imagePullPolicy: IfNotPresent
          args:
            - -timeout=120s
            - -wait
            - tcp://{{ .Values.operations_app.datasource.host }}:3306
      {{- if eq "string" (printf "%T" .Values.extraInitContainers) }}
    {{ tpl .Values.extraInitContainers . | indent 6 }}
          {{- else }}
    {{ toYaml .Values.extraInitContainers | indent 6 }}
          {{- end }}
          {{- end }}          
      volumes:
        - name: ph-ee-config
          configMap:
            name: ph-ee-config
     {{- if .Values.messagegateway.extraVolumeMounts | default .Values.messagegateway.deployment.extraVolumeMounts }}
  {{ toYaml ( .Values.messagegateway.extraVolumeMounts | default .Values.messagegateway.deployment.extraVolumeMounts ) | indent 8 }}
          {{- end }}
        {{- if .Values.messagegateway.extraContainers }}
  {{ tpl .Values.messagegateway.extraContainers . | indent 6 }}
        {{- end }}
{{- end }}